//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoundTheCorner.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblCuisine
    {
        public int CuisineID { get; set; }
        public string CuisineName { get; set; }
        public int VendorID { get; set; }
        public int MenuID { get; set; }
    }
}
