//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoundTheCorner.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMenuItem
    {
        public int itemID { get; set; }
        public int menuID { get; set; }
        public string itemName { get; set; }
        public decimal price { get; set; }
        public byte[] picture { get; set; }
        public string description { get; set; }
        public int MenuSectionID { get; set; }
    }
}
