//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoundTheCorner.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblMenu()
        {
            this.TblMenuItems = new HashSet<TblMenuItem>();
            this.TblMenuSections = new HashSet<TblMenuSection>();
        }
    
        public int menuID { get; set; }
        public int vendorID { get; set; }
        public bool isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMenuItem> TblMenuItems { get; set; }
        public virtual TblVendor TblVendor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblMenuSection> TblMenuSections { get; set; }
    }
}
