//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoundTheCorner.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblOrder()
        {
            this.TblOrderItems = new HashSet<TblOrderItem>();
        }
    
        public int orderID { get; set; }
        public int userID { get; set; }
        public int vendorID { get; set; }
        public System.DateTime orderDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblOrderItem> TblOrderItems { get; set; }
        public virtual TblUser TblUser { get; set; }
        public virtual TblVendor TblVendor { get; set; }
    }
}
