//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoundTheCorner.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVendorLocation
    {
        public int VendorID { get; set; }
        public System.DateTime Datetime { get; set; }
        public int LocationX { get; set; }
        public int LocationY { get; set; }
    }
}
