//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoundTheCorner.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblVendor
    {
        public int vendorID { get; set; }
        public int OwnerID { get; set; }
        public string CompanyName { get; set; }
        public string CompanyEmail { get; set; }
        public int LicenseNumber { get; set; }
        public System.DateTime inspectionDate { get; set; }
        public string bio { get; set; }
        public string Website { get; set; }
    }
}
